### ISSUE TITLE
Cannot install mutter-x11-scaling on Arch

### ISSUE THREAD

**Issue by mmnaseri** [puxplaying/mutter-x11-scaling#18]
I am on Gnome `40.4.0` right now and running X11 with kernel version 5.14.12-arch1-1. When I try to install via yay, this is what I get:

```
Summary of Failures:

104/106 mutter:core+mutter/native/headless / native-headless                                           TIMEOUT        60.77s   killed by signal 9 SIGKILL
105/106 mutter:core+mutter/ref-test/sanity / ref-test-sanity                                           TIMEOUT        60.51s   killed by signal 9 SIGKILL


Ok:                 104 
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            2   

Full log written to /home/milad/.cache/yay/mutter-x11-scaling/src/build/meson-logs/testlog.txt
A connection to the bus can't be made
=
```

A few lines before that I see the following warnings:

```
Window manager warning: Failed to set environment variable GNOME_SETUP_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable XAUTHORITY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable WAYLAND_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
```

**Comment by puxplaying** [comment]
It seems you are trying to build the AUR version, which is not the same as my project on Github. I do not maintain the AUR version, so please build from source as described in the readme.

> When I try to install via yay

**Comment by mind-overflow** [comment]
I'm sorry @mmnaseri but the solution you provided is related to another problem.  
In fact, I was having both problems - firstly, the infamous `Logical monitors not adjacent` one, which made compilation fail almost instantly for every single ninja package (giving something like 100/107 fails). This is easily fixed by either disabling fractional-scaling or deleting the `~/.config/monitors.xml` file and restarting the session.  
  
And both the link you provided, and your explanation ("I removed the external screen"), seem to be related to this issue I just described: by removing your secondary screen there is literally no other monitor apart from the integrated one, so of course it can't say that the two monitors are not adjacent. And the thread on the EnOS forum was opened by a guy with this same issue (I looked at the logfile he posted and it literally is the non-adjacent-monitors issue). Extract from the posted log:  
```
Bail out! mutter-FATAL-WARNING: Failed to read monitors config file '/home/assaf/.config/monitors.xml': Logical monitors not adjacent
```  
  
As I said, I had this issue but resolved it by deleting the XML file.
The issue you opened is however related to something completely different, which I am now having after fixing the other one.
I understand (and I'm glad) that you were able to fix your issue, and I'm also thankful that you posted it for others to see - however, it is completely misleading, because the solution you posted has nothing to do with error:
```
GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
```  
  
Which you originally reported and which I'm also having.
I am on Arch, running GNOME 41.1 on Xorg & Wayland (the issue happens with both). My AUR helper is paru. The issue is happening both with paru and by cloning @puxplaying's GitHub repo and compiling with `makepkg` as described in the README file.  
  
I'm kindly asking to reopen this issue so we can try to find the correct solution.  
Here's the full log of me trying to compile the git repo under Wayland: https://pastebin.com/raw/K9jkiF6K

I'm now going to log out and try compiling again from Xorg and provide the other log.

**Comment by puxplaying** [comment]
@mind-overflow 
The meson time-out errors in your log come from the _check() function of the PKGBUILD. Therefore it is recommended to build the package in a clean chroot. I will disable the meson test with version 41.2-1, to avoid build problems in the future. Every release is tested on my side in a clean chroot including meson test anyway.
